import React from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import { B2BDashboardSnapshot, OrganizationSummary, RecommendationDatum } from '@/lib/b2b-dashboard';

export type DashboardPackage = 'lite' | 'standard';

interface PilotOperationsExportData {
  dataCoverageScore: number;
  validatedCoverage: number;
  analyticsCoverage: number;
  backlogCount: number;
  highPrioritySegments: number;
  unknownSegmentCount: number;
  unclassifiedReadinessCount: number;
  staleRecordsCount: number;
  staleRate: number;
}

interface SuccessMetricsExportData {
  uniqueEntitiesCount: number;
  retestedEntitiesCount: number;
  retestCoverageRate: number;
  avgRetestCadenceDays: number | null;
  improvementDeltaAvg: number | null;
  closureRate: number;
  milestone30: { passed: boolean; note: string };
  milestone60: { passed: boolean; note: string };
  milestone90: { passed: boolean; note: string };
}

interface B2BPilotPackPDFDocumentProps {
  pack: DashboardPackage;
  organizationLabel: string;
  segmentLabel: string;
  snapshot: B2BDashboardSnapshot;
  pilotOps: PilotOperationsExportData;
  successMetrics: SuccessMetricsExportData;
  recommendations: RecommendationDatum[];
  portfolio: OrganizationSummary[];
  generatedBy: string;
  generatedAt: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 10,
    color: '#0f172a',
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 18,
    fontWeight: 800,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#334155',
    marginBottom: 14,
  },
  section: {
    marginTop: 12,
    border: '1pt solid #e2e8f0',
    borderRadius: 8,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
    color: '#1e293b',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
  },
  label: {
    color: '#475569',
    fontSize: 9,
  },
  value: {
    color: '#0f172a',
    fontWeight: 700,
    fontSize: 9,
  },
  bullet: {
    marginBottom: 4,
    fontSize: 9,
    lineHeight: 1.45,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '1pt solid #cbd5e1',
    paddingBottom: 4,
    marginBottom: 4,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1pt solid #e2e8f0',
    paddingVertical: 4,
  },
  colLarge: { width: '38%' },
  colMed: { width: '22%' },
  colSmall: { width: '20%' },
  footnote: {
    marginTop: 8,
    fontSize: 8,
    color: '#64748b',
    lineHeight: 1.4,
  },
});

function fmtPercent(value: number): string {
  return `${value.toFixed(1)}%`;
}

function fmtScore(value: number | null): string {
  return value === null ? '-' : value.toFixed(1);
}

function fmtDays(value: number | null): string {
  return value === null ? '-' : `${value.toFixed(1)} hari`;
}

export function B2BPilotPackPDFDocument({
  pack,
  organizationLabel,
  segmentLabel,
  snapshot,
  pilotOps,
  successMetrics,
  recommendations,
  portfolio,
  generatedBy,
  generatedAt,
}: B2BPilotPackPDFDocumentProps) {
  const isStandard = pack === 'standard';

  return (
    <Document title={`Omnifit_B2B_Pilot_${organizationLabel}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Omnifit B2B Pilot Export Pack ({pack === 'lite' ? 'Lite' : 'Standard'})</Text>
        <Text style={styles.subtitle}>
          Scope: {organizationLabel} | Pivot: {segmentLabel} | Generated by: {generatedBy} | {generatedAt}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Snapshot</Text>
          <View style={styles.row}><Text style={styles.label}>Total Participants</Text><Text style={styles.value}>{snapshot.totalParticipants}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Operating Model</Text><Text style={styles.value}>{snapshot.operatingModel}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Dominant Readiness</Text><Text style={styles.value}>{snapshot.dominantReadiness}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Average Score</Text><Text style={styles.value}>{fmtScore(snapshot.avgScore)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Validated Coverage</Text><Text style={styles.value}>{fmtPercent(pilotOps.validatedCoverage)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Analytics Coverage</Text><Text style={styles.value}>{fmtPercent(pilotOps.analyticsCoverage)}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Pilot Operations</Text>
          <View style={styles.row}><Text style={styles.label}>Data Coverage Score</Text><Text style={styles.value}>{pilotOps.dataCoverageScore}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Validation Backlog</Text><Text style={styles.value}>{pilotOps.backlogCount}</Text></View>
          <View style={styles.row}><Text style={styles.label}>High Priority Segments</Text><Text style={styles.value}>{pilotOps.highPrioritySegments}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Data Quality Gaps</Text><Text style={styles.value}>{pilotOps.unknownSegmentCount + pilotOps.unclassifiedReadinessCount}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Stale Signals</Text><Text style={styles.value}>{pilotOps.staleRecordsCount} ({fmtPercent(pilotOps.staleRate)})</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Success Metrics 30-60-90</Text>
          <View style={styles.row}><Text style={styles.label}>Retest Coverage</Text><Text style={styles.value}>{fmtPercent(successMetrics.retestCoverageRate)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Average Retest Cadence</Text><Text style={styles.value}>{fmtDays(successMetrics.avgRetestCadenceDays)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Improvement Delta Avg</Text><Text style={styles.value}>{fmtScore(successMetrics.improvementDeltaAvg)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Closure Rate</Text><Text style={styles.value}>{fmtPercent(successMetrics.closureRate)}</Text></View>
          <Text style={styles.bullet}>- 30 hari: {successMetrics.milestone30.passed ? 'PASS' : 'HOLD'} | {successMetrics.milestone30.note}</Text>
          <Text style={styles.bullet}>- 60 hari: {successMetrics.milestone60.passed ? 'PASS' : 'HOLD'} | {successMetrics.milestone60.note}</Text>
          <Text style={styles.bullet}>- 90 hari: {successMetrics.milestone90.passed ? 'PASS' : 'HOLD'} | {successMetrics.milestone90.note}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top Tactical Recommendations</Text>
          {recommendations.length === 0 ? (
            <Text style={styles.bullet}>- Belum ada rekomendasi yang dapat disusun dari data saat ini.</Text>
          ) : (
            recommendations.map((item) => (
              <View key={item.segment} style={{ marginBottom: 6 }}>
                <Text style={styles.bullet}>- {item.segment} [{item.priority}] - {item.rationale}</Text>
                {item.actions.map((action) => (
                  <Text key={`${item.segment}-${action}`} style={[styles.bullet, { marginLeft: 8 }]}>• {action}</Text>
                ))}
              </View>
            ))
          )}
        </View>

        {isStandard && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Tenant Portfolio (Top 8)</Text>
            <View style={styles.tableHeader}>
              <Text style={[styles.label, styles.colLarge]}>Organization</Text>
              <Text style={[styles.label, styles.colMed]}>Participants</Text>
              <Text style={[styles.label, styles.colSmall]}>Avg Score</Text>
              <Text style={[styles.label, styles.colSmall]}>Validated</Text>
            </View>
            {portfolio.slice(0, 8).map((item) => (
              <View key={item.name} style={styles.tableRow}>
                <Text style={[styles.value, styles.colLarge]}>{item.name}</Text>
                <Text style={[styles.value, styles.colMed]}>{item.count}</Text>
                <Text style={[styles.value, styles.colSmall]}>{fmtScore(item.avgScore)}</Text>
                <Text style={[styles.value, styles.colSmall]}>{fmtPercent(item.validatedRate)}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footnote}>
          Catatan metodologi: Retest Coverage dihitung dari entitas yang memiliki minimal 2 assessment. Improvement Delta memakai selisih skor terakhir vs skor pertama per entitas. Closure Rate dihitung dari segmen prioritas tinggi yang mencapai validatedRate minimal 80% dan lowReadinessRate di bawah 20%.
        </Text>
      </Page>
    </Document>
  );
}
