// scripts/generate-doc.mjs
import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.error("❌ ERROR: GEMINI_API_KEY tidak ditemukan di .env.local");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(apiKey);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

async function autoGenerateDocs() {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.log("⚠️ Cara penggunaan: node scripts/generate-doc.mjs <lokasi_file_kode> <nama_file_output.md>");
    process.exit(1);
  }

  const sourcePath = path.resolve(__dirname, '..', args[0]);
  const outputFileName = args[1];
  const outputDir = path.resolve(__dirname, '..', 'public', 'docs');
  const outputPath = path.join(outputDir, outputFileName);

  try {
    console.log(`\n📄 Membaca file kode: ${args[0]}...`);
    const sourceCode = fs.readFileSync(sourcePath, 'utf8');

    if (!fs.existsSync(outputDir)){
        fs.mkdirSync(outputDir, { recursive: true });
    }

    console.log(`🧠 Membangunkan Agen AI untuk memetakan arsitektur dan navigasi...`);
    
    const prompt = `Anda adalah AI Prompt Engineer dan System Architect ahli untuk aplikasi Omnifit.
    Tugas Anda adalah membedah kode React/Next.js berikut untuk menghasilkan "System Instruction & Navigation Manual" berformat Markdown (.md). 
    PENTING: File ini BUKAN sekadar untuk dibaca manusia, melainkan akan dikonsumsi oleh Agen AI (OpenClaw) sebagai memori referensi utamanya untuk memandu pengguna secara interaktif.

    ATURAN PENULISAN MUTLAK (SYSTEM PROMPT UNTUK OPENCLAW):
    1. ALUR KETERKAITAN (ECOSYSTEM FLOW): Buat bagian "## Alur Keterkaitan Sistem" (1 paragraf padat). Jelaskan fungsi utama halaman ini dalam arsitektur aplikasi.
    2. STATE & KONDISI PENGGUNA (KRITIS): Pisahkan penjelasan fitur berdasarkan status. (Misal: Apa yang dilihat Pengguna Anonim/Belum Login, Pengguna Sudah Login, Role Admin, dan Role Asesor). Hal ini akan mencegah Agen AI memberikan arahan rute ke pengguna yang salah.
    3. PANDUAN PENGGUNAAN & EXACT ROUTING (SANGAT KRITIS): 
       - Pindai secara menyeluruh SEMUA fungsi \`router.push()\` dan komponen \`<Link href="...">\` di dalam kode.
       - Anda WAJIB menyertakan rute navigasi menggunakan format Hyperlink Markdown persis: \`[Nama Aksi/Tombol](/rute-ekstrak)\`. 
       - Contoh yang Benar: "Bila pengguna ingin ke Dasbor, arahkan klik ke [Brankas Modul Saya](/dashboard)".
       - Contoh Salah (DILARANG): "Arahkan pengguna ke halaman /dashboard".
       - JANGAN mengarang URL. Gunakan HANYA URL yang secara eksplisit tertulis di source code.
    4. INTERAKSI MODAL & ALERT: Catat dengan jelas apabila sebuah interaksi tidak berpindah URL, melainkan membuka Modal/Pop-up (contoh: \`FeedbackModal\`, \`SystemCapabilitiesModal\`) atau memicu notifikasi Toast.
    5. SOLUSI KENDALA (TROUBLESHOOTING): Berikan panduan penyelesaian masalah dengan menganalisis parameter error yang ada di dalam source code (contoh: Token kadaluarsa, draf gagal dimuat karena tidak ada LocalStorage).
    6. FORMAT & GAYA BAHASA: Gunakan Bahasa Indonesia yang sangat deklaratif, lugas, dan instruksional. JANGAN gunakan block markdown (seperti \`\`\`markdown) pada awal atau akhir output, langsung hasilkan teks murni.

    KODE SUMBER YANG HARUS DIANALISIS:
    ${sourceCode}
    
    `;

    const result = await model.generateContent(prompt);
    const markdownContent = result.response.text();

    fs.writeFileSync(outputPath, markdownContent.trim());
    console.log(`✅ BERHASIL! Dokumentasi navigasi telah ditulis ke: public/docs/${outputFileName}\n`);

  } catch (error) {
    console.error("❌ Terjadi kesalahan:", error.message);
  }
}

autoGenerateDocs();